package com.zebra.main.model.externaldb

data class TransferLogDetailsExModel (
    var RowId: Int? = null,
    var LocationId: String? = null,
    var LocationName: String? = null,
    var PlotNo: String? = null,
    var FellingSectionNumber: String? = null,
    var HarvestCropsId: String? = null,
    var InStockId: String? = null,
    var TreeNumber: String? = null,
    var WoodSpeciesCode: String? = null,
    var SBBLabel: String? = null,
    var F1: String? = null,
    var F2: String? = null,
    var T1: String? = null,
    var T2: String? = null,
    var Length_dm: String? = null,
    var Volume: String? = null,
    var WoodSpeciesId: String? = null,
    var FellingSectionId: String? = null,
    var LogQuality: String? = null,
    var LogStatus: String? = null,
    var BarCode: String? = null,
    var CreatedDate: String? = null,
    var Note_F: String? = null,
    var Note_T: String? = null,
    var Note_L: String? = null,
    var HoleVolume: String? = null,
    var GrossVolume: String? = null,
    var RetributionStatus: String? = null,
    var ExportExaminationStatus: String? = null,
    var PurchaseID:String? = null
)