package com.zebra.main.activity.purchase

data class ExternalScannedLogsModel(
    var RowID:Int = 0,
    var LocationId:Int = 0,
    var WoodSpeciesId:Int = 0,
    var FellingSectionId:Int = 0,
    var PurchaseId:Int = 0,
    var EntryMode:Int = 0,
    var LocationName: String? = null,
    var FellingSectionNumber: String? = null,
    var TreeNumber: String? = null,
    var WoodSpeciesCode: String? = null,
    var F1: String? = null,
    var F2: String? = null,
    var T1: String? = null,
    var T2: String? = null,
    var Length_dm: String? = null,
    var Volume: String? = null,
    var LogQuality: String? = null,
    var LogStatus: String? = null,
    var BarCode: String? = null,
    var UpdatedDate: String? = null,
    var Note_F: String? = null,
    var Note_T: String? = null,
    var Note_L: String? = null,
    var HoleVolume: String? = null,
    var GrossVolume: String? = null,
    var RetributionStatus: String? = null,
    var ExportExaminationStatus: String? = null,
    var UpdatedBy: String? = null,
    var PurchaseNo: String? = null,
    var LHT1: String? = null,
    var LHT2: String? = null,
    var LHF1: String? = null,
    var LHF2: String? = null,
    var LHVolume: String? = null
)